### ISSUE TITLE
Erro na importação do CSS

### ISSUE THREAD

**Issue by guilherme-gjv** [GabGab-dev/html.sexo#4]
O nome do arquivo CSS foi alterado, mas na importação do HTML, ele está com o nome antigo. Isso faz com que o CSS da página não carregue.

**Comment by gabriel-andss** [comment]
- Alterei o que estava errado
- Modificação no CSS

![image](https://user-images.githubusercontent.com/100449982/155832720-11e24c0d-e6c4-45f2-bd9a-b6156bb6b8a8.png)
